version: '3'
services:
  hello:
    build: './services/hello'
    ports:
      - "3001:3000"
  bye:
    build: './services/bye'
    ports:
      - "3002:3000"
  auth:
    build: './services/auth'
    ports:
      - "3003:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./config/auth.conf:/etc/nginx/sites-available/auth.conf
      - ./config/hello.conf:/etc/nginx/sites-available/hello.conf
      - ./config/bye.conf:/etc/nginx/sites-available/bye.conf
    depends_on:
      - hello
      - bye
      - auth
