version: '3'
services:
  hello:
    build: './hello'
    ports:
      - "3001:3000"
  bye:
    build: './bye'
    ports:
      - "3002:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hello
      - bye
